info:
  model: int-scaffold
packages:
- gitBranch: main
  gitServerName: rahulsivakumar
  gitUrl: https://github.com/Rahul-Sivakumar-IBM
  gitUsername: Rahul-Sivakumar-IBM
  name: CritProject
- gitBranch: '1.0'
  gitServerName: rahulsivakumar
  gitUrl: https://github.com/Rahul-Sivakumar-IBM
  gitUsername: Rahul-Sivakumar-IBM
  name: TPPWithVar
version: '1.0'
