version: 1.0.0
info:
  model: int-scaffold
packages:
- name: CritProject
  gitServerName: rahulsivakumar
  gitUrl: https://github.com/Rahul-Sivakumar-IBM
  gitUsername: Rahul-Sivakumar-IBM
  gitBranch: release/1.0.0
- name: TPPWithVar
  gitServerName: rahulsivakumar
  gitUrl: https://github.com/Rahul-Sivakumar-IBM
  gitUsername: Rahul-Sivakumar-IBM
  gitBranch: "1.0"
